# Generated by Django 3.1.5 on 2021-01-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publshed_date',
            new_name='published_date',
        ),
    ]
